/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    vehicles: Vehicle;
    media: Media;
    inquiries: Inquiry;
    'part-categories': PartCategory;
    stores: Store;
    parts: Part;
    invoices: Invoice;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'part-categories': PartCategoriesSelect<false> | PartCategoriesSelect<true>;
    stores: StoresSelect<false> | StoresSelect<true>;
    parts: PartsSelect<false> | PartsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    settings: Setting;
    'estimator-config': EstimatorConfig;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'estimator-config': EstimatorConfigSelect<false> | EstimatorConfigSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  title: string;
  year?: number | null;
  /**
   * URL path: /vehicles/<slug>. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  status: 'draft' | 'published' | 'for-sale' | 'sold';
  /**
   * Who owns this build + its private ledger. Only admins can reassign.
   */
  owner?: (number | null) | User;
  featured?: boolean | null;
  /**
   * Manual sort (lower = first).
   */
  order?: number | null;
  category?: ('lifts' | 'street' | 'overland' | 'performance') | null;
  clientTruck?: string | null;
  /**
   * Short blurb for the showroom card.
   */
  summary?: string | null;
  /**
   * Card + hero image.
   */
  coverImage?: (number | null) | Media;
  /**
   * Shown on the vehicle spec-sheet page. Drag to reorder.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  beforeImage?: (number | null) | Media;
  afterImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specs?: {
    stance?: string | null;
    wheels?: string | null;
    engine?: string | null;
    transmission?: string | null;
    drivetrain?: string | null;
    gearRatio?: string | null;
    differential?: string | null;
    performance?: string | null;
  };
  completionTime?: string | null;
  estimatedCost?: number | null;
  /**
   * Shown when status is For sale.
   */
  salePrice?: number | null;
  /**
   * Optional build budget target (private — drives the Garage Ledger later).
   */
  budgetTarget?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'owner';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  status?: ('new' | 'read' | 'replied' | 'archived') | null;
  /**
   * The build this inquiry is about, if any.
   */
  vehicle?: (number | null) | Vehicle;
  message: string;
  /**
   * Which page/form the inquiry came from.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "part-categories".
 */
export interface PartCategory {
  id: number;
  name: string;
  slug?: string | null;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores".
 */
export interface Store {
  id: number;
  name: string;
  website?: string | null;
  phone?: string | null;
  /**
   * Your account # (private).
   */
  accountNumber?: string | null;
  /**
   * Alternate names this vendor appears as on invoices (helps AI matching).
   */
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parts".
 */
export interface Part {
  id: number;
  name: string;
  vehicle: number | Vehicle;
  category?: (number | null) | PartCategory;
  store?: (number | null) | Store;
  partNumber?: string | null;
  quantity?: number | null;
  /**
   * Price each ($).
   */
  unitPrice?: number | null;
  /**
   * qty × unit (auto).
   */
  lineTotal?: number | null;
  status?: ('wishlist' | 'ordered' | 'received' | 'installed' | 'returned') | null;
  purchaseDate?: string | null;
  notes?: string | null;
  /**
   * Set when created from an uploaded invoice.
   */
  sourceInvoice?: (number | null) | Invoice;
  /**
   * Inherited from the vehicle. Only admins can change it.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  vehicle: number | Vehicle;
  /**
   * AI-detected; confirm/adjust.
   */
  store?: (number | null) | Store;
  invoiceNumber?: string | null;
  invoiceDate?: string | null;
  subtotal?: number | null;
  tax?: number | null;
  shipping?: number | null;
  total?: number | null;
  /**
   * Review/edit, then Confirm to create parts.
   */
  lineItems?:
    | {
        description: string;
        partNumber?: string | null;
        quantity?: number | null;
        unitPrice?: number | null;
        lineTotal?: number | null;
        /**
         * AI-suggested; confirm/adjust.
         */
        category?: (number | null) | PartCategory;
        id?: string | null;
      }[]
    | null;
  reviewStatus?: ('pending-review' | 'confirmed') | null;
  /**
   * Inherited from the vehicle.
   */
  owner?: (number | null) | User;
  /**
   * Raw AI output (debug).
   */
  aiRaw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'part-categories';
        value: number | PartCategory;
      } | null)
    | ({
        relationTo: 'stores';
        value: number | Store;
      } | null)
    | ({
        relationTo: 'parts';
        value: number | Part;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  slug?: T;
  status?: T;
  owner?: T;
  featured?: T;
  order?: T;
  category?: T;
  clientTruck?: T;
  summary?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  beforeImage?: T;
  afterImage?: T;
  description?: T;
  challenge?: T;
  solution?: T;
  specs?:
    | T
    | {
        stance?: T;
        wheels?: T;
        engine?: T;
        transmission?: T;
        drivetrain?: T;
        gearRatio?: T;
        differential?: T;
        performance?: T;
      };
  completionTime?: T;
  estimatedCost?: T;
  salePrice?: T;
  budgetTarget?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  status?: T;
  vehicle?: T;
  message?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "part-categories_select".
 */
export interface PartCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores_select".
 */
export interface StoresSelect<T extends boolean = true> {
  name?: T;
  website?: T;
  phone?: T;
  accountNumber?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parts_select".
 */
export interface PartsSelect<T extends boolean = true> {
  name?: T;
  vehicle?: T;
  category?: T;
  store?: T;
  partNumber?: T;
  quantity?: T;
  unitPrice?: T;
  lineTotal?: T;
  status?: T;
  purchaseDate?: T;
  notes?: T;
  sourceInvoice?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  vehicle?: T;
  store?: T;
  invoiceNumber?: T;
  invoiceDate?: T;
  subtotal?: T;
  tax?: T;
  shipping?: T;
  total?: T;
  lineItems?:
    | T
    | {
        description?: T;
        partNumber?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        category?: T;
        id?: T;
      };
  reviewStatus?: T;
  owner?: T;
  aiRaw?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  tagline?: string | null;
  heroHeadline?: string | null;
  heroImage?: (number | null) | Media;
  storyTitle?: string | null;
  storyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  storyImage?: (number | null) | Media;
  contactEmail?: string | null;
  phone?: string | null;
  location?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  shareImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estimator-config".
 */
export interface EstimatorConfig {
  id: number;
  /**
   * Short blurb shown above the estimator.
   */
  intro?: string | null;
  /**
   * Truck platforms a customer can start from.
   */
  platforms?:
    | {
        name: string;
        /**
         * Starting build cost ($).
         */
        basePrice: number;
        minYear?: number | null;
        maxYear?: number | null;
        type?: ('fullsize' | 'midsize' | 'heavy' | 'classic') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Build options. Lift / wheels / tires are single-choice; the rest are add-ons.
   */
  features?:
    | {
        name: string;
        price: number;
        group: 'lift' | 'wheels' | 'tires' | 'performance' | 'exterior' | 'interior' | 'other';
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Range +/- shown around the estimate (percent).
   */
  contingencyPct?: number | null;
  disclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  tagline?: T;
  heroHeadline?: T;
  heroImage?: T;
  storyTitle?: T;
  storyContent?: T;
  storyImage?: T;
  contactEmail?: T;
  phone?: T;
  location?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  shareImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estimator-config_select".
 */
export interface EstimatorConfigSelect<T extends boolean = true> {
  intro?: T;
  platforms?:
    | T
    | {
        name?: T;
        basePrice?: T;
        minYear?: T;
        maxYear?: T;
        type?: T;
        id?: T;
      };
  features?:
    | T
    | {
        name?: T;
        price?: T;
        group?: T;
        description?: T;
        id?: T;
      };
  contingencyPct?: T;
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}